language: java

script:
  - ./gradlew assemble
  - ./gradlew check

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

before_install:
  - ./gradlew --version
  - java -version

matrix:
  include:
    - dist: trusty
      group: edge
      jdk: oraclejdk9
      sudo: false
